# Generated by Django 5.2.4 on 2025-07-14 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Hi-Tech Engineering Services', max_length=100)),
                ('description', models.TextField(default='With over 26 years of experience, Hi-Tech Engineering Services delivers top-quality elevator maintenance, overhauling, and modernization with a commitment to excellence and rapid response times.')),
                ('phone_1', models.CharField(default='031-2477499', max_length=20)),
                ('phone_2', models.CharField(default='02136369171', max_length=20)),
                ('email', models.EmailField(default='info@hitechservices.com', max_length=254)),
                ('address', models.TextField(default='Karachi, Pakistan')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='company/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Company Information',
            },
        ),
    ]
